_wandb:
    value:
        cli_version: 0.26.0
        e:
            a0yrek2gz3flvjxtu9o8mq82qbf1rwfc:
                codePath: c:\Users\user\Desktop\DS_practice\Lab 7 - Intro to deep learning.ipynb
                codePathLocal: Lab 7 - Intro to deep learning.ipynb
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "255382777856"
                        used: "155931996160"
                email: melissavioletvs@gmail.com
                executable: c:\Users\user\Desktop\DS_practice\.venv\Scripts\python.exe
                git:
                    commit: d7cad9e299627d6a35bcfc6ae946f2a86585f082
                    remote: https://github.com/melissaviolet/app_development.git
                host: CYBERSPACE
                memory:
                    total: "8462397440"
                os: Windows-10-10.0.18362-SP0
                program: c:\Users\user\Desktop\DS_practice\Lab 7 - Intro to deep learning.ipynb
                python: CPython 3.13.5
                root: c:\Users\user\Desktop\DS_practice
                startedAt: "2026-04-23T10:37:24.009504Z"
                writerId: a0yrek2gz3flvjxtu9o8mq82qbf1rwfc
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
            "4": 3.13.5
            "5": 0.26.0
            "8":
                - 1
                - 3
            "12": 0.26.0
            "13": windows-amd64
